global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'bot'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8999' ]
        labels:
          application: 'bot'

  - job_name: 'scrapper'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8998' ]
        labels:
          application: 'scrapper'
