/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.repository.jooq;

import edu.java.domain.repository.jooq.tables.Chat;
import edu.java.domain.repository.jooq.tables.Link;
import edu.java.domain.repository.jooq.tables.LinkChat;
import edu.java.domain.repository.jooq.tables.records.ChatRecord;
import edu.java.domain.repository.jooq.tables.records.LinkChatRecord;
import edu.java.domain.repository.jooq.tables.records.LinkRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] {Chat.CHAT.CHAT_ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] {Link.LINK.URL}, true);
    public static final UniqueKey<LinkChatRecord> CONSTRAINT_4 = Internal.createUniqueKey(LinkChat.LINK_CHAT,
        DSL.name("CONSTRAINT_4"),
        new TableField[] {LinkChat.LINK_CHAT.URL, LinkChat.LINK_CHAT.CHAT_ID},
        true
    );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinkChatRecord, LinkRecord> CONSTRAINT_47 =
        Internal.createForeignKey(LinkChat.LINK_CHAT,
            DSL.name("CONSTRAINT_47"),
            new TableField[] {LinkChat.LINK_CHAT.URL},
            Keys.CONSTRAINT_2,
            new TableField[] {Link.LINK.URL},
            true
        );
    public static final ForeignKey<LinkChatRecord, ChatRecord> CONSTRAINT_470 =
        Internal.createForeignKey(LinkChat.LINK_CHAT,
            DSL.name("CONSTRAINT_470"),
            new TableField[] {LinkChat.LINK_CHAT.CHAT_ID},
            Keys.CONSTRAINT_1,
            new TableField[] {Chat.CHAT.CHAT_ID},
            true
        );
}
