/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.repository.jooq;

import edu.java.domain.repository.jooq.tables.Chat;
import edu.java.domain.repository.jooq.tables.Link;
import edu.java.domain.repository.jooq.tables.LinkChat;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>LINK_CHAT</code>.
     */
    public static final LinkChat LINK_CHAT = LinkChat.LINK_CHAT;
}
