app:
  baseUrls:
    github: https://api.github.com
    stackOverflow: https://api.stackexchange.com/2.3
    bot: http://localhost:8090
  scheduler:
    enable: true
    interval: 30s
    force-check-delay: 10s

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
