/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.repository.jooq.tables.records;

import edu.java.domain.repository.jooq.tables.LinkChat;
import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LinkChatRecord extends UpdatableRecordImpl<LinkChatRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK_CHAT.URL</code>.
     */
    public void setUrl(@NotNull String value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK_CHAT.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getUrl() {
        return (String) get(0);
    }

    /**
     * Setter for <code>LINK_CHAT.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK_CHAT.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<String, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return LinkChat.LINK_CHAT.URL;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return LinkChat.LINK_CHAT.CHAT_ID;
    }

    @Override
    @NotNull
    public String component1() {
        return getUrl();
    }

    @Override
    @NotNull
    public Long component2() {
        return getChatId();
    }

    @Override
    @NotNull
    public String value1() {
        return getUrl();
    }

    @Override
    @NotNull
    public Long value2() {
        return getChatId();
    }

    @Override
    @NotNull
    public LinkChatRecord value1(@NotNull String value) {
        setUrl(value);
        return this;
    }

    @Override
    @NotNull
    public LinkChatRecord value2(@NotNull Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkChatRecord values(@NotNull String value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkChatRecord
     */
    public LinkChatRecord() {
        super(LinkChat.LINK_CHAT);
    }

    /**
     * Create a detached, initialised LinkChatRecord
     */
    @ConstructorProperties({"url", "chatId"})
    public LinkChatRecord(@NotNull String url, @NotNull Long chatId) {
        super(LinkChat.LINK_CHAT);

        setUrl(url);
        setChatId(chatId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinkChatRecord
     */
    public LinkChatRecord(edu.java.domain.repository.jooq.tables.pojos.LinkChat value) {
        super(LinkChat.LINK_CHAT);

        if (value != null) {
            setUrl(value.getUrl());
            setChatId(value.getChatId());
            resetChangedOnNotNull();
        }
    }
}
