app:
  telegram-token: ${token}
  baseUrls:
    scrapper: http://localhost:8080
  rateLimiter:
    enable: true
    limit: 50
    refill: 50
  retry:
    backoffPolicy: exponential
    attempts: 4
    delay: 10000
    jitter: 0.5
    codes: 400, 406, 500
  topic:
    name: "bot_updates"
    partitions: 10
    replicas: 1
  deadTopic:
    name: "bot_updates_dlq"
    partitions: 10
    replicas: 1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    bootstrapAddress: localhost:9092
    consumer:
      groupId: 1
      autoOffsetReset: earliest

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
